export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const TEST_DISPATCH = 'TEST_DISPATCH';

export const GET_PENDING_PSYCHOLOGIST_PROFILES = 'GET_PENDING_PSYCHOLOGIST_PROFILES';
export const GET_PENDING_MOTIVATIONAL_SPEAKER_PROFILES = 'GET_PENDING_MOTIVATIONAL_SPEAKER_PROFILES';
export const GET_PENDING_MOTIVATIONAL_WRITER_PROFILES = 'GET_PENDING_MOTIVATIONAL_WRITER_PROFILES';

export const GET_PENDING_HEALTH_GYM_INSTRUCTOR_PROFILES = 'GET_PENDING_HEALTH_GYM_INSTRUCTOR_PROFILES';
export const APPROVE_PROFILE = 'APPROVE_PROFILE';
export const DELETE_PROFILE_APPROVAL_REQUEST = 'DELETE_PROFILE_APPROVAL_REQUEST';

export const GET_REGISTERED_PATIENT_PROFILES = 'GET_REGISTERED_PATIENT_PROFILES';
export const GET_REGISTERED_PSYCHOLOGIST_PROFILES = 'GET_REGISTERED_PSYCHOLOGIST_PROFILES';

export const GET_PSYCHOLOGIST_PROFILES = 'GET_PSYCHOLOGIST_PROFILES';
export const GET_MOTIVATIONAL_SPEAKER_PROFILES = 'GET_MOTIVATIONAL_SPEAKER_PROFILES';
export const GET_MOTIVATIONAL_WRITER_PROFILES = 'GET_MOTIVATIONAL_WRITER_PROFILES';
export const GET_HEALTH_GYM_INSTRUCTOR_PROFILES = 'GET_HEALTH_GYM_INSTRUCTOR_PROFILES';

export const SUBMIT_ARTICLE_BLOG_POST = 'SUBMIT_ARTICLE_BLOG_POST';
export const DELETE_ARTICLE_BLOG_POST = 'DELETE_ARTICLE_BLOG_POST';
export const APPROVED_ARTICLE_BLOG_POST_LOADING = 'APPROVED_ARTICLE_BLOG_POST_LOADING';
export const GET_APPROVED_ARTICLE_BLOG_POSTS = 'GET_APPROVED_ARTICLE_BLOG_POSTS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SUBMIT_DAILY_HEALTH_EXERCISE_BLOG_POST = 'SUBMIT_DAILY_HEALTH_EXERCISE_BLOG_POST';
export const DELETE_DAILY_HEALTH_EXERCISE_BLOG_POST = 'DELETE_DAILY_HEALTH_EXERCISE_BLOG_POST';
export const GET_APPROVED_DAILY_HEALTH_EXERCISE_BLOG_POSTS = 'GET_APPROVED_DAILY_HEALTH_EXERCISE_BLOG_POSTS';
export const APPROVED_DAILY_HEALTH_EXERCISE_BLOG_POST_LOADING = 'APPROVED_DAILY_HEALTH_EXERCISE_BLOG_POST_LOADING';

export const REGISTER_COMPLAINT_QUERY = 'REGISTER_COMPLAINT_QUERY';

export const GET_ARTICLE_BLOG_POST_REQUESTS = 'GET_ARTICLE_BLOG_POST_REQUESTS';
export const APPROVE_ARTICLE_BLOG_POST_REQUEST = 'APPROVE_ARTICLE_BLOG_POST_REQUEST';
export const DELETE_ARTICLE_BLOG_POST_REQUEST = 'DELETE_ARTICLE_BLOG_POST_REQUEST';
export const ARTICLE_BLOG_POST_REQUESTS_LOADING = 'ARTICLE_BLOG_POST_REQUESTS_LOADING';

export const GET_DAILY_HEALTH_EXERCISE_POST_REQUESTS = 'GET_DAILY_HEALTH_EXERCISE_POST_REQUESTS';
export const APPROVE_DAILY_HEALTH_EXERCISE_POST_REQUEST = 'APPROVE_DAILY_HEALTH_EXERCISE_POST_REQUEST';
export const DELETE_DAILY_HEALTH_EXERCISE_POST_REQUEST = 'DELETE_DAILY_HEALTH_EXERCISE_POST_REQUEST';
export const DAILY_HEALTH_EXERCISE_POST_REQUESTS_LOADING = 'DAILY_HEALTH_EXERCISE_POST_REQUESTS_LOADING';

export const SUBMIT_MOTIVATIONAL_VIDEO = 'SUBMIT_MOTIVATIONAL_VIDEO';
export const GET_APPROVED_MOTIVATIONAL_VIDEOS = 'GET_APPROVED_MOTIVATIONAL_VIDEOS';
export const APPROVED_MOTIVATIONAL_VIDEOS_LOADING = 'APPROVED_MOTIVATIONAL_VIDEOS_LOADING'; 
export const DELETE_MOTIVATIONAL_VIDEO = 'DELETE_MOTIVATIONAL_VIDEO';

export const APPROVE_MOTIVATIONAL_VIDEO_POST_REQUEST = 'APPROVE_MOTIVATIONAL_VIDEO_POST_REQUEST'; 
export const GET_MOTIVATIONAL_VIDEO_POST_REQUESTS = 'GET_MOTIVATIONAL_VIDEO_POST_REQUESTS'; 
export const MOTIVATIONAL_VIDEO_POST_REQUESTS_LOADING = 'MOTIVATIONAL_VIDEO_POST_REQUESTS_LOADING'; 
export const DELETE_MOTIVATIONAL_VIDEO_POST_REQUEST = 'DELETE_MOTIVATIONAL_VIDEO_POST_REQUEST';

export const SELECT_TEXT_CHAT_SESSION = 'SELECT_TEXT_CHAT_SESSION';
export const SELECT_VIDEO_CHAT_SESSION = 'SELECT_VIDEO_CHAT_SESSION';
export const CHECK_AVAILABLE_SLOTS = 'CHECK_AVAILABLE_SLOTS';
export const MAKE_PAYMENT_REQUEST = 'MAKE_PAYMENT_REQUEST';

export const GET_PATIENT_PAYMENT_REQUESTS = 'GET_PATIENT_PAYMENT_REQUESTS';
export const APPROVE_PATIENT_PAYMENT_REQUEST = 'APPROVE_PATIENT_PAYMENT_REQUEST';
export const DELETE_PATIENT_PAYMENT_REQUEST = 'DELETE_PATIENT_PAYMENT_REQUEST'; 

export const FILE_UPLOAD = 'FILE_UPLOAD';

export const SUBMIT_PROGRESS_REPORT = 'SUBMIT_PROGRESS_REPORT';
export const GET_PROGRESS_REPORTS = 'GET_PROGRESS_REPORTS';

export const SUBMIT_SUCCESS_STORY = 'SUBMIT_SUCCESS_STORY';

export const GET_PSYCHOLOGIST_SESSIONS = 'GET_PSYCHOLOGIST_SESSIONS';
export const GET_PATIENT_SESSIONS = 'GET_PATIENT_SESSIONS';

export const GIVE_PSYCHOLOGIST_FEEDBACK = 'GIVE_PSYCHOLOGIST_FEEDBACK';
export const GET_PSYCHOLOGIST_FEEDBACK = 'GET_PSYCHOLOGIST_FEEDBACK';

export const APPROVE_SUCCESS_STORY_REQUEST = 'APPROVE_SUCCESS_STORY_REQUEST'; 
export const GET_SUCCESS_STORY_REQUESTS = 'GET_SUCCESS_STORY_REQUESTS'; 
export const SUCCESS_STORY_REQUESTS_LOADING = 'SUCCESS_STORY_REQUESTS_LOADING'; 
export const DELETE_SUCCESS_STORY_REQUEST = 'DELETE_SUCCESS_STORY_REQUEST';

export const GET_TOP_RATED_PROFILES = 'GET_TOP_RATED_PROFILES';

export const GET_SUCCESS_STORIES = 'GET_SUCCESS_STORIES';















